import React from 'react'
import Navbar from '../../Components/Navbar'
import Image from 'next/image'
import {AiOutlineStar} from 'react-icons/ai'
import StarRating from '../../Components/StarRating'
import Head from 'next/head'
import axios from 'axios'
import { useRouter } from 'next/dist/client/router'
import SmallCard from '../../Components/SmallCard'

const StayList = ({data}) => {
  const orig = `https://virtserver.swaggerhub.com/HERIBUDIYANA/Air-Bnb/1.0.0/`
  const router = useRouter()
  console.log(data)
   
  
  return (
        <>
        <div className='bg-white h-screen'>
        <Head>
            <title>Hyrule Travel - Find A New Place</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
        </Head>
        <Navbar/>
        <div className='px-5 py-2'>
            <h1 className='text-2xl mb-4 font-semibold text-black'>List Of Stays</h1>
            <div className='hidden lg:inline-flex mb-4 space-x-3 text-gray-800 whitespace-nowrap'>
                <p className='buttons'>Cancel your order</p>
                <p className='buttons'>Rooms</p>
                <p className='buttons'>HEHE HAHA</p>
                <p className='buttons'>Discount Price</p>
            </div>
        </div>
        <div className="flex bg-white">
        <div className="flex flex-col px-3 py-2 w-screen lg:w-[50%] h-full lg:px-5 rounded-xl">

          {data.map(item => (
            <SmallCard
            title= {item.title}
            deskripsi = {item.description}
            address = {item.address}
            price = {item.price}
            images = {item.images}
            ids = {item.id}
            rating = {item.ratting}
            />
          ))}
        </div>
        <div className="hidden lg:inline-flex w-[50%] bg-white">
          <Image
            src={"/Maps.png"}
            className="w-screen h-screen object-cover"
            width={100}
            height={100}
          />
        </div>
       </div>
      </div>
    </>

  );
};

export default StayList;

export async function getServerSideProps() {
    const getHomeStays = await axios.get(`https://virtserver.swaggerhub.com/HERIBUDIYANA/Air-Bnb/1.0.0/homestays`)
    const data = getHomeStays.data.data
    return { 
        props: {
            data: data
        } 
    }
  }
  