import React, { useEffect } from "react";
import { useState } from "react";
import Navbar from "../../Components/Navbar";
import { useRouter } from "next/router";
import axios from "axios";
import HomeDetail from "../../Components/HomeDetail";
import Cookies from "js-cookie";
import Head from "next/head";

const Detailhomestay = () => {
  const [homestayDetail, setHomestayDetails] = useState([]);
  const [checkin, setCheckin] = useState();
  const [checkout, setCheckout] = useState();

  const name = Cookies.get("name");
  const token = Cookies.get("token");
  const router = useRouter();
  const details = router?.query?.ids;
  console.log(router?.query?.ids);
  console.log(details);

  const config = {
    headers: { Authorization: `Bearer ${token}` },
  };

  const orderHomestay = async () => {
    console.log(checkin);
    console.log(checkout);
    await axios
      .post(
        `https://limagroup.my.id/reserves`,
        {
          homestay_id: details,
          check_in: checkin,
          check_out: checkout,
        },
        config
      )
      .then((response) => console.log(response))
      .catch((err) => {
        console.log(err);
      });
  };

  const get_Details = async () => {
    await axios
      .get(`https://limagroup.my.id/homestays/${details}`, config)
      .then((response) => {
        console.log(response.data.data);
        setHomestayDetails(response.data.data);
      })
      .catch((error) => {
        console.log(error);
      });
  };

  useEffect(() => {
    get_Details();
  }, []);


  return (
    <div className="bg-white h-full w-full">
      <Head>
        <title>Hyrule Travel - Find A New Place</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <Navbar
        profile={() => router.push(`/${name}/edit-user`)}
        host={() => router.push(`/${name}/become-host`)}
        history={() => router.push(`/${name}/history`)}
      />
      <div>
        {homestayDetail ?
          <HomeDetail
            title={homestayDetail.Title}
            deskripsi={homestayDetail.Description}
            lokasi={homestayDetail.Address}
            harga={homestayDetail.Price}
            komentar={homestayDetail.Comments}
            gambar={homestayDetail.Images}
            order={() => check()}
            checkin={(e) => setCheckin(e.target.value)}
            checkout={(e) => setCheckout(e.target.value)}
          />
          :
          <p className="text-black text-5xl">Loading</p>
        }
      </div>

    </div>
  );
};

export default Detailhomestay;
