import React, { useEffect } from "react";
import { useState } from "react";
import Navbar from "../../Components/Navbar";
import { useRouter } from "next/router";
import axios from "axios";
import HomeDetail from "../../Components/HomeDetail";
import Cookies from "js-cookie";
import Head from "next/head";

const Detailhomestay = () => {
  const [homestayDetail, setHomestayDetails] = useState([]);
  const [checkin, setCheckin] = useState();
  const [checkout, setCheckout] = useState();

  const name = Cookies.get("name");
  const token = Cookies.get("token");
  const router = useRouter();
  const details = router?.query?.ids;

  const config = {
    headers: { Authorization: `Bearer ${token}` },
  };

  const orderHomestay = async () => {
    await axios.post(
      `https://limagroup.my.id/reserves`,
      {
        homestay_id: details,
        check_in: checkin,
        check_out: checkout,
      },
      config
    );
  };

  const get_Details = async () => {
    await axios
      .get(`https://limagroup.my.id/homestays/${details}`, config)
      .then((response) => {
        setHomestayDetails(response.data.data);
      });
  };

  useEffect(() => {
    get_Details();
  }, []);

  return (
    <div className="bg-white h-full w-full">
      <Head>
        <title>Hyrule Travel - Find A New Place</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <Navbar
        profile={() => router.push(`/${name}/edit-user`)}
        host={() => router.push(`/${name}/become-host`)}
        history={() => router.push(`/${name}/history`)}
      />
      <div>
        {homestayDetail && (
          <HomeDetail
            title={homestayDetail.Title}
            deskripsi={homestayDetail.Description}
            lokasi={homestayDetail.Address}
            harga={homestayDetail.Price}
            komentar={"kolom komentar"}
            gambar={homestayDetail.Images}
            order={() => check()}
            checkin={(e) => setCheckin(e.target.value)}
            checkout={(e) => setCheckout(e.target.value)}
          />
        )}
      </div>
      <div>
        <label for="start" className="text-black">
          Checkin:
        </label>
        <input
          type="date"
          id="start"
          name="trip-start"
          min="2018-01-01"
          max="2025-12-31"
          data-date-format="DD MMMM YYYY"
          className=" text-black"
          onChange={(e) => setCheckin(e.target.value)}
        ></input>
      </div>
      <div className="w-1/2 ml-2">
        <label for="start" className="text-black">
          Checkout:
        </label>
        <input
          type="date"
          id="start"
          name="trip-start"
          min="2018-01-01"
          max="2025-12-31"
          data-date-format="DD MMMM YYYY"
          className=" text-black"
          onChange={(e) => setCheckout(e.target.value)}
        ></input>
      </div>
      <button
        className="bg-black p-3 rounded-xl font-bold mt-10 w-36"
        onClick={() => orderHomestay()}
      >
        Order
      </button>
    </div>
  );
};

export default Detailhomestay;
