
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Dashboard from './dashboard'
import LoginPage from './loginPage'
import RegisterPage from './registerPage'
import StayList from './stayList'




export default function Home() {
  return (
    <div className="h-100 w-100">
      <Head>
        <title>Hyrule Travel - Find A New Place</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen">
        <LoginPage/>
      </main>
    </div>
  );

}
