import React from 'react'
import Navbar from '../Components/Navbar'
import Head from 'next/head'

const triplist = () => {
  return (
    <div>
     <Head>
        <title>Hyrule Travel - Find A New Place</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
     </Head>
     <Navbar/>
     <div className='relative w-full h-screen bg-white'>
        <div className='w-[800px] mx-auto bg-white pl-5 pt-[100px]'>
            <h2 className='text-6xl text-black font-medium'>Your Trip List</h2>

            <div className='mt-10'>
                <div className='ruler-atas'></div>
                <h3 className='text-black font-medium my-5 text-3xl'>Villa Premium A3</h3>
                <select
                    name="cars"
                    id="cars"
                    className="bg-white mr-5 rounded-xl text-black shadow-2xl my-4 font-semibold w-64 border- pb-3"
                  >
                    <option className='text-black font-semibold' value="volvo">Check In Date</option>
                    <option className='text-black font-semibold' value="saab">Mastercard</option>
                    <option className='text-black font-semibold' value="mercedes">Paypal</option>
                    <option className='text-black font-semibold' value="audi">Kidney</option>
                  </select>
                <select
                    name="cars"
                    id="cars"
                    className="bg-white text-black rounded-xl shadow-2xl my-4 font-semibold w-64 border- pb-3"
                  >
                    <option className='text-black font-semibold' value="volvo">Check Out Date</option>
                    <option className='text-black font-semibold' value="saab">Mastercard</option>
                    <option className='text-black font-semibold' value="mercedes">Paypal</option>
                    <option className='text-black font-semibold' value="audi">Kidney</option>
                  </select>
                  <h4 className='text-black font-medium text-xl my-3'>Rp100.000 x 2 Night</h4>
                  <h3 className='text-black font-bold text-xl my-3'>Total Price : Rp200.000</h3>
            </div>
            
            <div className='mt-10'>
                <div className='ruler-atas'></div>
                <h3 className='text-black font-medium my-5 text-3xl'>Villa Premium A3</h3>
                <select
                    name="cars"
                    id="cars"
                    className="bg-white mr-5 rounded-xl text-black shadow-2xl my-4 font-semibold w-64 border- pb-3"
                  >
                    <option className='text-black font-semibold' value="volvo">Check In Date</option>
                    <option className='text-black font-semibold' value="saab">Mastercard</option>
                    <option className='text-black font-semibold' value="mercedes">Paypal</option>
                    <option className='text-black font-semibold' value="audi">Kidney</option>
                  </select>
                <select
                    name="cars"
                    id="cars"
                    className="bg-white text-black rounded-xl shadow-2xl my-4 font-semibold w-64 border- pb-3"
                  >
                    <option className='text-black font-semibold' value="volvo">Check Out Date</option>
                    <option className='text-black font-semibold' value="saab">Mastercard</option>
                    <option className='text-black font-semibold' value="mercedes">Paypal</option>
                    <option className='text-black font-semibold' value="audi">Kidney</option>
                  </select>
                  <h4 className='text-black font-medium text-xl my-3'>Rp100.000 x 2 Night</h4>
                  <h3 className='text-black font-bold text-xl my-3'>Total Price : Rp200.000</h3>
            </div>

        </div>
     </div>
    </div>
  )
}

export default triplist